version: '2'

services:
  angular:
    build: front-end
    ports:
      - "4200:4200"
    volumes:
      - ./front-end:/app
      - /app/node_modules/

  express:
    build: back-end
    ports:
      - "3000:3000"